version: '3.4'

services:
  express_api_architecture_prototype:
    image: express_api_architecture_prototype
    build: .
    environment:
      NODE_ENV: production
      PORT: 3000
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      REDIS_AUTH: ""
      DB_HOST: "localhost"
      DB_USER: "root"
      DB_PASSWORD: "root"
      DB_NAME: "api_test"
    ports:
      - 3000:3000
    depends_on: 
      - redis
  redis:
    image: redis
    ports:
      - 6379
  redis_commander:
    image: rediscommander/redis-commander
    ports: 
      - 6378:6378
    depends_on:
      - redis
    environment:
      PORT: 6378
      REDIS_PORT: 6379
      REDIS_HOST: "redis"
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "api_test"
  mysql_admin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment: 
      PMA_HOST: "mysql"
    depends_on:
      - mysql