version: '3.4'

services:
  express_api_architecture_prototype:
    image: express_api_architecture_prototype
    build: .
    environment:
      NODE_ENV: production
      PORT: 3000
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      REDIS_AUTH: ""
      DB_HOST: "localhost"
      DB_USER: "root"
      DB_PASSWORD: ""
      DB_NAME: "api_test"
    ports:
      - 3000:3000
    depends_on: 
      - redis
    volumes: 
      - .:/home/node/app
    command: /home/node/app/node_modules/.bin/nodemon server.js
  redis:
    image: redis
    ports:
      - 6379